---
title: "**Our Trees**"
listing:
  type: grid
  id: trees
  contents: tree-profiles/profiles
  filter-ui: true
---

## **Have Something to Share About Our Trees?**

Do you have a story related to a tree on Coe's campus you'd be comfortable sharing? Maybe just a picture with one of our trees? Whether you have a tree on campus that you're fond of for no particular reason, an amusing anecdote involving one of our trees, or a nostalgic memory of planting a tree after the 2020 derecho, we want to hear it! Numerical measurements can give us great insight into the physical impact of our trees, but your stories are the best way for us to understand just how valuable trees are in our personal lives and social systems.

If you have something (some words or a photo) you'd be willing to share, please consider contributing to the Coe Tree Archive. We will preserve what you submit alongside the other records maintained in the Coe Tree Archive, just click the button below.

<center><a class="button" href="https://forms.gle/6acapE5m9WgEFQmp6">Say Something About Our Trees!</a></center>

<br>

## **Tree Profiles**

::: {trees}
:::
